### ISSUE TITLE
Missing option of disconnecting the touch event from the relay

### ISSUE THREAD

**Issue by TeDeVPrime** [edwardtfn/TX-Ultimate-Easy#17]
Can we have an option for each button that disconnects from the physical relay?

For example i have a TX Ultimate on my entrance wall but there is only one light connected there.
the other two buttons on my 3-gang switch are for controlling other things in the room via home assistant.

if i press the 1st button the physical relay should toggle but if i press the other two buttons, i don't want the physical relays to activate or make any mechanical noises.

**Comment by edwardtfn** [comment]
Solved in `dev`
