### ISSUE TITLE
Request: Relay Light Mode should be different for each relay.

### ISSUE THREAD

**Issue by TeDeVPrime** [edwardtfn/TX-Ultimate-Easy#19]
The reason i need this is because that i just found out that 
if i want my light switch to always be on (so that my wifi lamp has power) the light on TX stays on and i can't turn it off until i toggle the relay off.

i can't turn the option completely off because i want it to work for the other two relays where one of them is for the light at the balcony

by having that option, i could also set Relay 1 and 3 to turn the bottom light on and Relay 2 to turn the top light on....
that way the distinction of what is on and what is off, will be much better from a distance.

**Comment by edwardtfn** [comment]
I believe this is now possible with the latest changes.
Could you please update your system ant try again? If the issue persists, pleas reopen this with a bit more of details. 😉
