### ISSUE TITLE
Light Left is losing it's settings if "LIGHT" turns on and off. Light Right works fine

### ISSUE THREAD

**Issue by TeDeVPrime** [edwardtfn/TX-Ultimate-Easy#21]
So this is my case scenario....

Light Right..... Red Pulse Slow - > On
Light Left..... Warm White Solid - > On

the doorbell rings....
LIGHT (the general one) ..... Rainbow effect fast - > On for 10 seconds then turn Off....

Home assistant thinks that Light Left is On when it isn't.....
but Light Right keeps working properly with Red Pulse Slow and On....

**Comment by edwardtfn** [comment]
Could you please update to the latest version and try again?
Please let me know the results.
