### ISSUE TITLE
Refactor suggestion - Splitting into multiple files (packages pattern)

### ISSUE THREAD

**Issue by ROBOT0-VT** [edwardtfn/TX-Ultimate-Easy#27]
Right now, I can only imagine that working with a single 2000-line file with the base config cannot be great for maintainability. I suggest splitting the `yaml` config using esphome's `packages` feature, to make this easier to work with.

A good example of this (and where I learned this) is [Karl Quinsland's TX Ultimate firmware](https://karlquinsland.com/sonoff-t5-esphome/), although there does not appear to be an easily-accessible repo for this example 😭

**Comment by edwardtfn** [comment]
Solved in DEV and will be part of the coming release.
It can be improved in the future, but a first step is done.

**Comment by edwardtfn** [comment]
Could you please update to the latest version and try again?
Please let me know the results.
