### ISSUE TITLE
After the last changes the Relay button lights no longer work

### ISSUE THREAD

**Issue by TeDeVPrime** [edwardtfn/TX-Ultimate-Easy#28]
@edwardtfn 
I did the new update and the swipe seems to be working fine now 
but i lost the lights when the relay is on.
am i doing something wrong? here is a screenshot

![image](https://github.com/user-attachments/assets/3a255e70-ad68-4089-a555-780df41e4726)

**Comment by edwardtfn** [comment]
I will take a look

**Comment by edwardtfn** [comment]
Could you please update to the latest version and try again?
Please let me know the results.

**Comment by TeDeVPrime** [comment]
@edwardtfn nope. it doesn't work. If i set my middle relay to Light as shown in the picture above... it will not turn on the light.

it is like the switch is attached to the relay mode and not the state of the button. 
if i turn the Relay 2 Mode back to a Relay.... then the lights on the switch come on

**Comment by iceteaSA** [comment]
@edwardtfn On my side (US-Variant 2-4 Gang) it is mostly working correctly, except only the right side LEDs are mapped correctly, the left side seems to be off, with the top LEDs coming on for the top gangs. Another issue is that state is not restored properly on boot. The status lights will still burn, and HA reports the lights to be on, but the relays are not triggered, meaning the actual lights are still off. Also, the LEDs reset back to white on boot if you have changed it.

**Comment by edwardtfn** [comment]
This should be fixed now. Could you please update your system and try it again?
