### ISSUE TITLE
some problem with  TX Ultimate 4 Gang US (T5-4-120)

### ISSUE THREAD

**Issue by mon3y78** [edwardtfn/TX-Ultimate-Easy#29]
Hi, I'm having some issues with the TX Ultimate 4 Gang US (T5-4-120):

If I turn on the light, I'm unable to turn it off again.
The same light doesn't fully illuminate (photo attached).
All the LEDs (top-right-left-bottom) are not correctly synchronized (I’m attaching a photo of the top light), and they don't turn off.
Have other people had the same problems?
I can't figure out how to correct the error!
![IMG_1343](https://github.com/user-attachments/assets/89eade38-2e1f-4072-9ed1-91a5a4782e13)
![IMG_1344](https://github.com/user-attachments/assets/dc982ddc-1525-4557-b790-760c56afee64)

**Comment by edwardtfn** [comment]
I can try to,duplicate the issues, however, I’m unsure if I fully understood all of those. Could you please provide more details of what was expected behaviour and how it is behaving for each of the issues you reported?

**Comment by mon3y78** [comment]
![image](https://github.com/user-attachments/assets/4070013a-4d02-4e18-9dbd-0831ceba57de)

**Comment by mon3y78** [comment]
🤔

**Comment by edwardtfn** [comment]
Sorry, I was quite busy those days...
I will look at this later today.

**Comment by mon3y78** [comment]
Unfortunately, the problem hasn't been resolved. A short section of the LEDs is not lighting up.
Additionally, when I turn on the LEDs, it's not possible to turn them off. The switch on the panel turns off, but the LEDs remain on.
Is there anything I can do to help you understand the issues?
Thank you for your efforts.

**Comment by edwardtfn** [comment]
Could you please update to the latest version and try again?
Please let me know the results.
