### ISSUE TITLE
Request: ability to set the color and brightness of status lights from the ui

### ISSUE THREAD

**Issue by cavazosomar** [edwardtfn/TX-Ultimate-Easy#57]
Currently the status lights are only white at 100% brightness. With this enhancement the color and brightness status lights should be able to be configured directly in the ui

**Comment by edwardtfn** [comment]
I've just added an option to expose the relay indicator's lights to Home Assistant. With that, you will be able to set the settings for those lights, which will be used when the respective relay turns on.
Please update your system and let me know if this is ok.
I will look later for a way to set how those lights should be when the relay is off.

**Comment by cavazosomar** [comment]
The button to expose the relay indicators didn't do anything for me, however the entities did appear on the disabled list. I just had to enable them manually

**Comment by edwardtfn** [comment]
And are those working properly after you enable it manually?

**Comment by cavazosomar** [comment]
So I checked again after updating to the latest version and I can see that the entities are getting exposed ( and hidden) when toggling the switch, however they are added to the entities list as disabled every time either the toggle switch is pressed or when updating the firmware even if I enabled them previously, so they have to be enabled every time. I think it would be better if the were added as enabled by default

**Comment by edwardtfn** [comment]
WIth the latest changes those entities shouldn't be disabled when exposed:
https://github.com/edwardtfn/TX-Ultimate-Easy/pull/77/files

So either you're not with the latest build (which right now is [![Version][version-shield]](https://github.com/edwardtfn/TX-Ultimate-Easy/tags) or your system is maintaining the old settings in flash (and I'm not sure what can be done in this case other than a full reset which will discard all other settings saved 😞 ).

It's also important to note that some changes requires your system to be restarted before those become effective. I've added a sensor named **Pending Restart Status** on the **Diagnostic** area which should indicate a problem when your system is pending restart to make some change valid.

[version-shield]: https://img.shields.io/github/v/tag/edwardtfn/TX-Ultimate-Easy?label=version
[version]: https://github.com/edwardtfn/TX-Ultimate-Easy/tags

**Comment by cavazosomar** [comment]
Well I just updated to v2024.12.27 and the entities still appear as disabled, as seen in the screenshot: 

![hass-tx-ultimate](https://github.com/user-attachments/assets/e7c92f88-a56f-4a61-8ca2-462abc82ed31)

I suppose it's not that much of a hassle to add those entities manually from time to time once the code become more mature and the updates become less frequent
