### ISSUE TITLE
With 2024.12.9 I can't disable button action

### ISSUE THREAD

**Issue by edwardtfn** [edwardtfn/TX-Ultimate-Easy#59]
Witch 2024.12.9 I can't disable button action

_Originally posted by @mon3y78 in https://github.com/edwardtfn/TX-Ultimate-Easy/issues/51#issuecomment-2559020909_

**Comment by edwardtfn** [comment]
@mon3y78, what do you mean? You really can't disable or you can disable but the system ignores your selection and toggles the relays anyways?

**Comment by edwardtfn** [comment]
Ok, I can duplicate the issue sometimes. Similar to what @TeDeVPrime reported since a while.
I will look at this ASAP.

**Comment by edwardtfn** [comment]
Could you please try it again with the latest version from a minute ago?

**Comment by mon3y78** [comment]
Now work
