### ISSUE TITLE
Led indicator of sliding

### ISSUE THREAD

**Issue by edwardtfn** [edwardtfn/TX-Ultimate-Easy#7]
Request 5:
When i slide from left to right....
i want a color animation at the top and bottom to go from left to right
and the opposite if i slide right to left

*Suggested by @TeDeVPrime on #2*

**Comment by TeDeVPrime** [comment]
no need to bother with this. it is a gimmick and i can easily do it with an automation now that i have the led sides available to use them as i want. but thank you for considering it!
